import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/navbar/NavBar";
import { twClass } from "@/utils/twClass";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={twClass(inter.className, "")}>
        <NavBar />
        <main className="flex min-h-screen flex-col items-center justify-between p-4 md:p-8 lg:p-24">
          {children}
        </main>
        {modal}
      </body>
    </html>
  );
}
